# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'carrierwave', '~> 2.2', '>= 2.2.2'
gem 'figaro', '~> 1.2'
gem 'fog', '~> 2.2'
gem 'mini_magick', '~> 4.11'
gem 'rainbow', '~> 3.1', '>= 3.1.1'
gem 'tty-progressbar', '~> 0.18.2'
gem 'tty-prompt', '~> 0.23.1'
